**❓ What is NumPy**

NumPy is a high performance numerical library that gives Python the power to work with large datasets efficiently. It provides fast, memory optimized arrays and mathematical tools that form the core of every machine learning workflow.

**⚙️ Why NumPy is Important in Machine Learning**

NumPy (Numerical Python) is the **foundation of all Machine Learning libraries in Python**.  
Almost every ML library — including Pandas, Scikit-Learn, TensorFlow, and PyTorch — is built on top of NumPy.

**🔍 Why It’s Essential**
- 🧮 **Efficient Computation:** Handles large numerical datasets faster than Python lists.
- 🧱 **Data Representation:** ML data (features & labels) are stored as matrices/tensors → NumPy arrays.
- ⚙️ **Vectorization:** Executes math operations on entire arrays without loops.
- 🔢 **Linear Algebra Support:** Used in gradient descent, covariance, matrix multiplication, etc.
- 🤝 **Integration:** Works seamlessly with Pandas, Matplotlib, Scikit-Learn, TensorFlow, and others.

> 💡 *If Python is the language of Machine Learning, NumPy is its mathematics engine.*

---

**Install & import Numpy library**

In [1]:
%pip install numpy==2.3.5

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.9 MB 6.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/12.9 MB 3.4 MB/s eta 0:00:04
   ------- -------------------------------- 2.4/12.9 MB 4.0 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.9 MB 4.3 MB/s eta 0:00:03
   ------------ --------------------------- 4.2/12.9 MB 4.2 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.9 MB 3.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.9 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.9 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.9 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.9 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 8.4/12.9 MB 3.7 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.9 MB 3.7 MB/s eta 0:00:02
   ---


[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install --upgrade pip

  Using cached pip-26.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 26.0.1
    Uninstalling pip-26.0.1:
      Successfully uninstalled pip-26.0.1
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


**Compare list and numpy array**

In [7]:
import time
import numpy as np

n = 1_000_000  # 1000000

py_list = list(range(n))
np_array = np.arange(n)

print(len(py_list))
print(len(np_array))

print(py_list[0:5])
print(np_array[0:5])

# Python list
t1 = time.time()
py_result = [x * 2 for x in py_list]   # multiply each element by 2
t2 = time.time()

# NumPy array (same operation)
t3 = time.time()
np_result = np_array * 2               # multiply each element by 2
t4 = time.time()

print("List time:", t2 - t1)
print("NumPy time:", t4 - t3)

1000000
1000000
[0, 1, 2, 3, 4]
[0 1 2 3 4]
List time: 0.07745075225830078
NumPy time: 0.00417780876159668


**Creating numpy arrays**

In [13]:
arr1 = np.array([1, 2, 3, 4, 5])  # 1D
arr2 = np.array([[1, 8.2, 3], [4, 5.3, 6]]) # 2D
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) # 3D


print("1D array:", arr1)
print("\n2D array:\n", arr2)
print("\n3D array:\n", arr3)

1D array: [1 2 3 4 5]

2D array:
 [[1.  8.2 3. ]
 [4.  5.3 6. ]]

3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
print(arr2)

[[1.  2.  3. ]
 [4.  5.3 6. ]]


In [16]:
# Array Attributes
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Data Type:", arr3.dtype)
print("Total Elements:", arr2.size)

Shape: (2, 3)
Dimensions: 2
Data Type: float64
Data Type: int64
Total Elements: 6


In [15]:
zeros = np.zeros((3, 3))
ones = np.ones((3, 2))
random_arr = np.random.rand(3, 3)
eye = np.eye(3)
range_arr = np.arange(0, 10, 2)



print(zeros)
print("---------")
print(ones)
print("---------")
print(random_arr)
print("---------")
print(eye)
print("---------")
print(range_arr)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
---------
[[0.00306892 0.22084268 0.92451034]
 [0.16634932 0.00466117 0.59248076]
 [0.30918031 0.72327053 0.97624957]]
---------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------
[0 2 4 6 8]


**indexing & slicing**

In [19]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr)
print("---------")
print(arr[0,2]) # individual element
print("---------")
print(arr[2])  # row access
print("---------")
print(arr[:, 1])  # column access

[[10 20 30]
 [40 50 60]
 [70 80 90]]
---------
30
---------
[70 80 90]
---------
[20 50 80]


**Array Operations**

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Dot Product", np.dot(a, b))
print("Cross Product", np.cross(a, b))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Dot Product 32
Cross Product [-3  6 -3]


**Reshaping & flattening**

In [17]:
arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
flattened = reshaped.flatten()


print(arr)
print("-----")
print(reshaped)
print("------")
print(flattened)

[1 2 3 4 5 6 7 8 9]
-----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------
[1 2 3 4 5 6 7 8 9]
